### ISSUE TITLE
Should we refactor to predefined options?

### ISSUE THREAD

**Issue by ju5t** [sensson/ansible-directadmin#3]
One of the more recent versions of DirectAdmin comes with support for predefined options. In the current setup we install CustomBuild before running the DirectAdmin installation, but this may be a cleaner, more future proof solution.

I'm not sure if this is required at this point though.

More information available here: [predefined options](https://docs.directadmin.com/getting-started/installation/overview.html#running-the-installation-with-predefined-options).

**Comment by HHawk** [comment]
Also license key has changed to a longer string. Which is required to be used.

**Comment by ju5t** [comment]
@HHawk this is a different issue. Can you open a new issue for this and perhaps create a PR for it? We'd like to keep issues on topic as much as possible.

**Comment by HHawk** [comment]
Nevermind. No worries..thought I was being helpful. Delete my post. Bye

Op 20 dec. 2021 21:01, om 21:01, ju5t ***@***.***> schreef:
***@***.*** this is a different issue. Can you open a new issue for this and

**Comment by ju5t** [comment]
Apparently there has been a license change too. See #4.
